
###
POST http://localhost:9000/api/clients
Content-Type: application/json

{
 "nom": "AAA",
 "prenom": "aaa"
}

###
GET http://localhost:9000/api/clients/1

###
GET http://localhost:9000/api/clients/1/comptes

###
POST http://localhost:9000/api/clients/2/comptes
Content-Type: application/json

{
   "solde" : 1000
}

###
GET http://localhost:9000/api/comptes/1

###
GET http://localhost:9000/api/clients/2

###
POST http://localhost:9000/api/clients
Content-Type: application/json

{ "nom" : "Durand", "prenom" : "Marcel" }

###
POST http://localhost:9000/api/clients/1/comptes
Content-Type: application/json

{ "solde" : 10000 }

###
GET http://localhost:9000/api/clients/1/comptes

###
GET http://localhost:9000/api/comptes/1

###
GET http://localhost:9000/api/comptes/2/operations

###
POST http://localhost:9000/api/comptes/2/operations
Content-Type: application/json

{ "valeur" : 100, "operationType" : "CREDIT" }

###
POST http://localhost:9000/api/comptes/2/operations
Content-Type: application/json

{ "valeur" : 100, "operationType" : "DEBIT" }

###
POST http://localhost:9000/api/comptes/1/operations/virements
Content-Type: application/json

{ "valeur" : 100, "idCompteDestinataire" : 3 }

###
DELETE http://localhost:9000/api/comptes/2

